"use client";

/* eslint-disable @next/next/no-img-element -- local, dimensioned WebP assets are intentional for this static project gallery */

import { FormEvent, useEffect, useRef, useState } from "react";
import { ArrowDownRight, ArrowRight, ArrowUpRight, Building2, Check, ChevronRight, ClipboardCheck, Factory, Hammer, HardHat, Menu, PencilRuler, ShieldCheck, X } from "lucide-react";
import { HeroConstructionScene } from "./HeroConstructionScene";

const services = [
  { icon: Building2, title: "Construcción residencial", text: "Viviendas contemporáneas donde diseño, presupuesto y ejecución avanzan como un solo sistema." },
  { icon: PencilRuler, title: "Edificios corporativos", text: "Espacios de trabajo eficientes, flexibles y alineados con la identidad de cada organización." },
  { icon: Factory, title: "Proyectos industriales", text: "Infraestructura productiva planificada alrededor de la operación, la seguridad y el crecimiento futuro." },
  { icon: Hammer, title: "Remodelación y ampliación", text: "Transformamos estructuras existentes con intervenciones precisas y continuidad operativa." },
  { icon: HardHat, title: "Supervisión de obra", text: "Control técnico, documental y financiero en cada hito importante del proyecto." },
  { icon: ClipboardCheck, title: "Diseño y planificación", text: "Convertimos necesidades reales en alcances claros, planos coordinados y rutas de ejecución viables." },
];
const projects = [
  { name: "Residencial Loma Alta", category: "Residencial", location: "Tegucigalpa", year: "2026", area: "640 m²", image: "/images/residencial.webp", alt: "Arquitectura contemporánea de volúmenes claros" },
  { name: "Centro Corporativo Nexo", category: "Corporativo", location: "San Pedro Sula", year: "2025", area: "2,850 m²", image: "/images/corporativo.webp", alt: "Interior corporativo con estructura de acero y concreto" },
  { name: "Complejo Logístico Norte", category: "Industrial", location: "Puerto Cortés", year: "2025", area: "8,200 m²", image: "/images/industrial.webp", alt: "Equipo ejecutando estructura de acero en obra" },
  { name: "Renovación Casa Patio", category: "Remodelación", location: "Valle de Ángeles", year: "2024", area: "390 m²", image: "/images/obra.webp", alt: "Equipo realizando fundición de concreto" },
];
const process = [["01", "Diagnóstico", "Entendemos objetivos, sitio, operación y restricciones."], ["02", "Propuesta", "Definimos alcance, inversión estimada y equipo necesario."], ["03", "Planificación", "Coordinamos diseños, permisos, compras y cronograma."], ["04", "Construcción", "Ejecutamos con control visible de calidad, costo y avance."], ["05", "Entrega", "Documentamos, verificamos y acompañamos la puesta en marcha."]];

function Stat({ value, suffix, label }: { value: number; suffix?: string; label: string }) {
  const [display, setDisplay] = useState(0); const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const node = ref.current; if (!node) return; const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches; const observer = new IntersectionObserver(([entry]) => { if (!entry.isIntersecting) return; if (reduced) setDisplay(value); else { const start = performance.now(); const tick = (now: number) => { const progress = Math.min(1, (now - start) / 1000); setDisplay(Math.round(value * (1 - Math.pow(1 - progress, 3)))); if (progress < 1) requestAnimationFrame(tick); }; requestAnimationFrame(tick); } observer.disconnect(); }); observer.observe(node); return () => observer.disconnect(); }, [value]);
  return <div className="stat" ref={ref}><strong>{display}{suffix}</strong><span>{label}</span></div>;
}

export function NexoLanding() {
  const [menuOpen, setMenuOpen] = useState(false); const [filter, setFilter] = useState("Todos"); const [sent, setSent] = useState(false); const [sending, setSending] = useState(false);
  const filters = ["Todos", "Residencial", "Corporativo", "Industrial", "Remodelación"];
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; setSending(true); window.setTimeout(() => { setSending(false); setSent(true); form.reset(); }, 700); };
  return <main>
    <a className="skip-link" href="#contenido">Saltar al contenido</a>
    <header className="site-header"><a className="brand" href="#inicio" aria-label="Nexo Constructora, inicio"><span className="brand-mark" aria-hidden="true">N</span><span>NEXO<small>CONSTRUCTORA</small></span></a><nav className="desktop-nav" aria-label="Navegación principal"><a href="#servicios">Servicios</a><a href="#proyectos">Proyectos</a><a href="#proceso">Proceso</a><a href="#contacto">Contacto</a></nav><a className="header-cta" href="#contacto">Solicitar cotización <ArrowUpRight size={16}/></a><button className="menu-button" type="button" aria-label="Abrir menú" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button>{menuOpen && <nav className="mobile-nav" aria-label="Navegación móvil">{["servicios","proyectos","proceso","contacto"].map((item) => <a key={item} href={`#${item}`} onClick={() => setMenuOpen(false)}>{item}</a>)}</nav>}</header>
    <section className="hero" id="inicio"><div className="hero-copy" id="contenido"><p className="eyebrow"><span/> Construcción · Diseño · Supervisión</p><h1>Precisión que<br/>se convierte<br/><em>en espacio.</em></h1><p className="lede">Acompañamos cada proyecto desde el primer plano hasta la entrega, con procesos claros y ejecución rigurosa.</p><div className="hero-actions"><a className="button-primary" href="#contacto">Cotizar un proyecto <ArrowUpRight size={18}/></a><a className="button-link" href="#proyectos">Explorar proyectos <ArrowDownRight size={17}/></a></div><div className="hero-metrics" aria-label="Métricas demostrativas"><div><strong>15+</strong><span>Años de<br/>experiencia</span></div><div><strong>120</strong><span>Proyectos<br/>ejecutados</span></div><div><strong>96%</strong><span>Entregas según<br/>planificación</span></div></div></div><div className="hero-visual"><div className="plan-label">NEXO / 01 <span>MODELO ESTRUCTURAL</span></div><HeroConstructionScene/><span className="coordinate coordinate-a">14°05&apos;N</span><span className="coordinate coordinate-b">87°13&apos;W</span><div className="visual-caption"><span>Interacción</span><p>Mueva el cursor para explorar la estructura</p></div></div></section>
    <section className="trust-strip" aria-label="Capacidades"><p>Diseñamos para el presente.<br/><strong>Construimos para permanecer.</strong></p><span>01&nbsp;&nbsp; Planificación integral</span><span>02&nbsp;&nbsp; Control de calidad</span><span>03&nbsp;&nbsp; Presupuesto transparente</span></section>
    <section className="section services" id="servicios"><div className="section-heading"><p className="eyebrow"><span/> Lo que hacemos</p><h2>Un solo equipo.<br/><em>Todo el proceso.</em></h2><p>Integramos diseño, planificación y ejecución para reducir incertidumbre y convertir cada decisión en avance real.</p></div><div className="service-grid">{services.map((service, index) => { const Icon = service.icon; return <article className="service-card" key={service.title}><div className="service-top"><span>0{index + 1}</span><Icon size={24} strokeWidth={1.4}/></div><h3>{service.title}</h3><p>{service.text}</p><ChevronRight size={18} className="service-arrow"/></article>; })}</div></section>
    <section className="projects section-dark" id="proyectos"><div className="projects-header"><div><p className="eyebrow"><span/> Obras seleccionadas</p><h2>Proyectos que<br/><em>hablan por sí solos.</em></h2></div><p>Cada obra es una respuesta distinta al lugar, al presupuesto y a la manera en que será utilizada.</p></div><div className="filter-bar" role="group" aria-label="Filtrar proyectos">{filters.map((item) => <button type="button" key={item} className={filter === item ? "active" : ""} aria-pressed={filter === item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="project-grid">{projects.filter((project) => filter === "Todos" || project.category === filter).map((project, index) => <article className={`project-card project-${index + 1}`} key={project.name}><div className="project-image"><img src={project.image} width="900" height="650" loading="lazy" alt={project.alt}/><span>{project.category}</span></div><div className="project-info"><div><h3>{project.name}</h3><p>{project.location} · {project.year}</p></div><strong>{project.area}</strong></div></article>)}</div></section>
    <section className="manifesto section"><div className="manifesto-image"><img src="/images/obra.webp" width="1200" height="900" loading="lazy" alt="Equipo coordinando el vertido de concreto en una obra"/><span>Control en campo / 04</span></div><div className="manifesto-copy"><p className="eyebrow"><span/> Nuestra forma de trabajar</p><h2>La confianza también<br/><em>se construye.</em></h2><p className="manifesto-lede">Una obra bien ejecutada empieza mucho antes de colocar el primer material: empieza con información clara y decisiones coordinadas.</p><ul>{["Comunicación directa durante toda la obra","Control visible de cambios y presupuesto","Coordinación entre diseño, ingeniería y campo","Calidad documentada en cada etapa"].map((item) => <li key={item}><Check size={16}/>{item}</li>)}</ul></div></section>
    <section className="process section" id="proceso"><div className="process-intro"><p className="eyebrow"><span/> De la idea a la entrega</p><h2>Un proceso claro.<br/><em>Sin cajas negras.</em></h2></div><div className="process-list">{process.map(([number,title,text]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div><ArrowRight size={18}/></article>)}</div></section>
    <section className="stats-section"><p className="eyebrow"><span/> Nexo en cifras</p><div className="stats-grid"><Stat value={15} suffix="+" label="años de experiencia"/><Stat value={86} suffix="K" label="m² construidos"/><Stat value={120} suffix="+" label="proyectos completados"/><Stat value={94} suffix="%" label="clientes satisfechos"/></div><small>* Cifras demostrativas para fines de presentación.</small></section>
    <section className="testimonial section"><ShieldCheck size={35} strokeWidth={1.25}/><blockquote>“Nexo convirtió un proyecto complejo en un proceso que podíamos entender y controlar. Cada decisión llegó con contexto, costo y una ruta clara.”</blockquote><p><strong>María Elena P.</strong><span>Cliente residencial · Testimonio demostrativo</span></p></section>
    <section className="contact" id="contacto"><div className="contact-intro"><p className="eyebrow"><span/> Empecemos una conversación</p><h2>Su próximo proyecto<br/><em>merece un buen inicio.</em></h2><p>Cuéntenos qué necesita. Nuestro equipo revisará la información y preparará el siguiente paso.</p><div className="contact-details"><a href="tel:+50422000000">+504 2200-0000</a><a href="mailto:proyectos@nexo.demo">proyectos@nexo.demo</a><span>Lun–Vie · 8:00–17:00</span></div></div><form onSubmit={submit}><div className="form-row"><label>Nombre<input name="nombre" autoComplete="name" required/></label><label>Empresa <span>(opcional)</span><input name="empresa" autoComplete="organization"/></label></div><div className="form-row"><label>Correo<input name="correo" type="email" autoComplete="email" required/></label><label>Teléfono<input name="telefono" type="tel" autoComplete="tel" required/></label></div><div className="form-row"><label>Tipo de proyecto<select name="tipo" required defaultValue=""><option value="" disabled>Seleccione una opción</option>{["Residencial","Corporativo","Industrial","Remodelación","Supervisión"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Ubicación<input name="ubicacion" required/></label></div><label>Cuéntenos sobre el proyecto<textarea name="mensaje" rows={4} required/></label><label className="privacy"><input type="checkbox" required/><span>Acepto que mis datos sean usados para responder esta solicitud demostrativa.</span></label><button className="submit-button" type="submit" disabled={sending}>{sending ? "Enviando…" : "Enviar solicitud"}<ArrowUpRight size={18}/></button><p className="form-note" aria-live="polite">{sent ? "Solicitud demostrativa recibida. En un sitio real, el equipo se pondría en contacto." : "Este formulario es una demostración y no envía datos a un servidor."}</p></form></section>
    <footer><div className="footer-brand"><a className="brand" href="#inicio"><span className="brand-mark">N</span><span>NEXO<small>CONSTRUCTORA</small></span></a><p>Planificamos con precisión.<br/>Construimos para permanecer.</p></div><div><strong>Explorar</strong><a href="#servicios">Servicios</a><a href="#proyectos">Proyectos</a><a href="#proceso">Proceso</a></div><div><strong>Contacto</strong><a href="mailto:proyectos@nexo.demo">Correo</a><a href="tel:+50422000000">Teléfono</a><a href="#contacto">Cotización</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Nexo Constructora · Sitio demostrativo</span><a href="/CREDITS.md">Créditos visuales</a></div></footer>
  </main>;
}
